// Display labels for vocabulary topic slugs (`vocabulary.topics`). Dependency-free: also
// runs in the browser (guest practice). Topics are free slugs on each word; a slug without
// a label here is shown with a readable fallback, so a new topic in the CMS never breaks the
// Practice page – add its label here when it is introduced.
//
// UI labels, not curriculum content. Review them with the A1 word lists.
export const VOCAB_TOPIC_LABELS = Object.freeze({
  begruessung: { de: "Begrüßung", en: "Greetings" },
  vorstellung: { de: "Sich vorstellen", en: "Introducing yourself" },
  herkunft: { de: "Herkunft", en: "Where you are from" },
  laender: { de: "Länder", en: "Countries" },
  sprachen: { de: "Sprachen", en: "Languages" },
  alphabet: { de: "Alphabet", en: "The alphabet" },
  zahlen: { de: "Zahlen", en: "Numbers" },
  fragen: { de: "Fragen", en: "Questions" },
  personen: { de: "Personen", en: "People" },
  familie: { de: "Familie", en: "Family" },
  beruf: { de: "Beruf", en: "Jobs" },
  arbeitsort: { de: "Arbeitsort", en: "Places of work" },
  kollegen: { de: "Kollegen", en: "Colleagues" },
  buero: { de: "Büro", en: "At the office" },
  jobsuche: { de: "Jobsuche", en: "Looking for a job" },
  schule: { de: "Schule", en: "School" },
  studium: { de: "Studium", en: "University" },
  kurs: { de: "Deutschkurs", en: "Language course" },
  stadt: { de: "Stadt", en: "In town" },
  gebaeude: { de: "Gebäude", en: "Buildings" },
  wege: { de: "Wege", en: "Directions" },
  verkehr: { de: "Verkehr", en: "Transport" },
  stadtbesichtigung: { de: "Stadtbesichtigung", en: "Sightseeing" },
  schilder: { de: "Schilder", en: "Signs" },
  lebensmittel: { de: "Lebensmittel", en: "Food" },
  getraenke: { de: "Getränke", en: "Drinks" },
  essen: { de: "Mahlzeiten", en: "Meals" },
  cafe: { de: "Im Café", en: "At the café" },
  einkaufen: { de: "Einkaufen", en: "Shopping" },
  mengen: { de: "Mengen", en: "Quantities" },
  preise: { de: "Preise", en: "Prices" },
  kaufhaus: { de: "Kaufhaus", en: "Department store" },
  kleidung: { de: "Kleidung", en: "Clothes" },
  farben: { de: "Farben", en: "Colours" },
  alltag: { de: "Alltag", en: "Everyday life" },
  uhrzeit: { de: "Uhrzeit", en: "Telling the time" },
  tageszeiten: { de: "Tageszeiten", en: "Times of day" },
  wochentage: { de: "Wochentage", en: "Days of the week" },
  monate: { de: "Monate", en: "Months" },
  jahreszeiten: { de: "Jahreszeiten", en: "Seasons" },
  datum: { de: "Datum", en: "Dates" },
  termine: { de: "Termine", en: "Appointments" },
  hobbys: { de: "Hobbys", en: "Hobbies" },
  feste: { de: "Feste", en: "Celebrations" },
  einladung: { de: "Einladung", en: "Invitations" },
  veranstaltungen: { de: "Veranstaltungen", en: "Events" },
  telefon: { de: "Telefon", en: "On the phone" },
  "e-mail": { de: "E-Mail", en: "E-mail" },
  technik: { de: "Technik", en: "Technology" },
  bank: { de: "Bank", en: "At the bank" },
  formular: { de: "Formulare", en: "Forms" },
  koerper: { de: "Körper", en: "The body" },
  krankheit: { de: "Krankheit", en: "Illness" },
  arztpraxis: { de: "Arztpraxis", en: "At the doctor's" },
  apotheke: { de: "Apotheke", en: "Pharmacy" },
  ratschlaege: { de: "Ratschläge", en: "Advice" },
  wohnen: { de: "Wohnen", en: "Living" },
  moebel: { de: "Möbel", en: "Furniture" },
  wohnungssuche: { de: "Wohnungssuche", en: "Flat hunting" },
  vergangenheit: { de: "Vergangenheit", en: "Talking about the past" },
  perfekt: { de: "Verben im Perfekt", en: "Verbs in the Perfekt" },
  reisen: { de: "Reisen", en: "Travel" },
  wetter: { de: "Wetter", en: "Weather" },
  meinung: { de: "Meinung", en: "Opinions" },
  modalverben: { de: "Modalverben", en: "Modal verbs" },
  praepositionen: { de: "Präpositionen", en: "Prepositions" },
  konjunktionen: { de: "Konjunktionen", en: "Conjunctions" },
  negation: { de: "Verneinung", en: "Saying no" },
});

// { de, en } for a topic slug; unknown slugs get "Some-topic" → "Some topic".
export function vocabTopicLabel(slug) {
  if (Object.hasOwn(VOCAB_TOPIC_LABELS, slug)) return VOCAB_TOPIC_LABELS[slug];
  const text = String(slug).replace(/-/g, " ");
  return { de: text.charAt(0).toUpperCase() + text.slice(1) };
}
