import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { cueHash, curriculumCues, requiredExerciseCues } from "@/lib/audio/cues";
import { expectedStaticKey, manifestEntrySchema } from "@/lib/audio/manifest";
import { parseMp3 } from "@/lib/audio/mp3";

// Offline verification of the generated curriculum audio (`bun run audio:verify`).
// Checks the manifest, the files in public/media/tts and the content against each other.
// Anything that could make a learner hear the wrong clip, or nothing, is an error.

const MIN_CLIP_SEC = 0.2;
const MAX_CLIP_SEC = 60;
const TEST_BLOCKS = new Set(["mini_test", "mastery_check"]);

function listFiles(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...listFiles(p));
    else out.push(p);
  }
  return out;
}

export function verifyAudio({ moduleDefs, manifestPath, mediaDir, allowOrphans = false }) {
  const errors = [];
  const warnings = [];
  const needed = curriculumCues(moduleDefs); // hash -> cue

  // 1. Manifest.
  let raw = [];
  if (!existsSync(manifestPath)) {
    errors.push(`Manifest not found: ${manifestPath}. Run \`bun run audio:generate\`.`);
  } else {
    try {
      const json = JSON.parse(readFileSync(manifestPath, "utf8"));
      if (!Array.isArray(json.entries)) errors.push("Manifest has no `entries` array.");
      else raw = json.entries;
    } catch (err) {
      errors.push(`Manifest is not valid JSON: ${err.message}`);
    }
  }

  const entries = new Map();
  const keys = new Map();
  for (const [i, r] of raw.entries()) {
    const parsed = manifestEntrySchema.safeParse(r);
    if (!parsed.success) {
      errors.push(`Manifest entry #${i} is invalid: ${parsed.error.issues.map((x) => `${x.path.join(".")}: ${x.message}`).join("; ")}`);
      continue;
    }
    const e = parsed.data;
    if (entries.has(e.hash)) errors.push(`Duplicate manifest entry for hash ${e.hash}.`);
    if (keys.has(e.key)) errors.push(`Two manifest entries point to the same file ${e.key}.`);
    entries.set(e.hash, e);
    keys.set(e.key, e.hash);

    const recomputed = cueHash({ text: e.text, voice: e.voiceRole, rate: e.rate, lang: e.lang });
    if (recomputed !== e.hash) errors.push(`${e.hash}: hash does not match its text/voice/rate ("${e.text}"). The entry was edited or is stale.`);
    if (e.driver !== "static") errors.push(`${e.hash}: driver "${e.driver}" – production audio must be static files.`);
    if (e.mime !== "audio/mpeg") errors.push(`${e.hash}: mime "${e.mime}" – production audio must be MP3.`);
    if (e.key !== expectedStaticKey(e.hash)) errors.push(`${e.hash}: file name ${e.key} does not match the hash (expected ${expectedStaticKey(e.hash)}).`);
    if (e.provider === "fake") errors.push(`${e.hash}: generated by the fake (silent) provider.`);
  }

  // 2. Content ↔ manifest.
  const missing = [...needed.keys()].filter((h) => !entries.has(h));
  for (const h of missing) errors.push(`Missing clip ${h}: ${needed.get(h).voice}/${needed.get(h).rate} "${needed.get(h).text}"`);
  const orphanEntries = [...entries.keys()].filter((h) => !needed.has(h));
  for (const h of orphanEntries) {
    (allowOrphans ? warnings : errors).push(`Manifest entry ${h} is not used by any content ("${entries.get(h).text}"). Remove it with \`bun run audio:generate -- --prune\`.`);
  }

  // 3. Files.
  const ttsDir = join(mediaDir, "tts");
  const onDisk = new Set(listFiles(ttsDir).map((p) => relative(mediaDir, p).split(sep).join("/")));
  for (const key of onDisk) {
    if (!keys.has(key)) errors.push(`File public/media/${key} is not in the manifest (orphan file).`);
  }
  const digests = new Map();
  const stats = { clips: 0, bytes: 0, durationSec: 0, sampleRates: new Set(), bitrates: new Set(), voices: {} };
  for (const e of entries.values()) {
    if (!onDisk.has(e.key)) {
      errors.push(`${e.hash}: file public/media/${e.key} is missing.`);
      continue;
    }
    const bytes = readFileSync(join(mediaDir, e.key));
    if (bytes.byteLength === 0) {
      errors.push(`${e.hash}: file ${e.key} is empty.`);
      continue;
    }
    if (e.size != null && e.size !== bytes.byteLength) errors.push(`${e.hash}: size ${bytes.byteLength} differs from the manifest (${e.size}).`);
    const mp3 = parseMp3(bytes);
    if (!mp3.ok) {
      errors.push(`${e.hash}: ${e.key} is not a valid MP3 (${mp3.error}).`);
      continue;
    }
    if (mp3.durationSec < MIN_CLIP_SEC) errors.push(`${e.hash}: only ${mp3.durationSec.toFixed(2)} s long ("${e.text}").`);
    if (mp3.durationSec > MAX_CLIP_SEC) errors.push(`${e.hash}: ${mp3.durationSec.toFixed(1)} s is longer than any curriculum clip should be.`);
    const chars = e.text.length;
    if (mp3.durationSec > 3 + chars * 0.25) warnings.push(`${e.hash}: ${mp3.durationSec.toFixed(1)} s seems long for ${chars} characters ("${e.text}").`);
    if (mp3.durationSec < chars * 0.02) warnings.push(`${e.hash}: ${mp3.durationSec.toFixed(1)} s seems short for ${chars} characters ("${e.text}").`);

    const digest = createHash("sha256").update(bytes).digest("hex");
    if (digests.has(digest)) warnings.push(`${e.hash} and ${digests.get(digest)} are byte-identical (duplicate generation).`);
    digests.set(digest, e.hash);

    stats.clips++;
    stats.bytes += bytes.byteLength;
    stats.durationSec += mp3.durationSec;
    stats.sampleRates.add(mp3.sampleRate);
    stats.bitrates.add(mp3.bitrateKbps);
    const v = e.providerVoice ?? e.voiceRole;
    stats.voices[v] = (stats.voices[v] ?? 0) + 1;
  }

  // 4. Listening exercises and the module test, reported per exercise.
  const valid = (h) => entries.has(h) && onDisk.has(entries.get(h).key);
  const listening = [];
  for (const def of moduleDefs) {
    const testSlugs = new Set(
      (def.lessons ?? []).flatMap((l) => l.blocks.filter((b) => b.exercise && (TEST_BLOCKS.has(b.type) || l.slug.includes("test"))).map((b) => b.exercise)),
    );
    for (const ex of def.exercises ?? []) {
      const required = requiredExerciseCues(ex);
      if (required.length === 0) continue;
      const absent = required.filter((c) => !valid(cueHash(c))).length;
      listening.push({ exercise: ex.slug, moduleTest: testSlugs.has(ex.slug), required: required.length, missing: absent });
      if (absent) errors.push(`${testSlugs.has(ex.slug) ? "Module test " : ""}exercise ${ex.slug}: ${absent} of ${required.length} required clip(s) unavailable.`);
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
    summary: {
      neededClips: needed.size,
      manifestEntries: entries.size,
      filesOnDisk: onDisk.size,
      validClips: stats.clips,
      totalMB: Math.round((stats.bytes / 1048576) * 100) / 100,
      totalMinutes: Math.round((stats.durationSec / 60) * 10) / 10,
      sampleRates: [...stats.sampleRates],
      bitratesKbps: [...stats.bitrates],
      voices: stats.voices,
      listeningExercises: listening.length,
      moduleTestListening: listening.filter((l) => l.moduleTest),
    },
  };
}
